version: "3"

# Example docker compose

services:

  app:
    image: ghcr.io/lanzani/mediapipe:l4t35.4.1-py3.8.10-ocv4.8.0-mp0.10.7-build
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - /home/:/home/
    devices:
      - /dev/snd
      - /dev/bus/usb
      - /dev/video0
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/tmp/.docker.xauth


# Note:
# You need to export DISPLAY=:0 on the host machine and run 'xhost +' to allow connections from the container