version: "3"

# Example docker compose

services:

  app:
    image: ghcr.io/lanzani/opencv:l4t35.4.1-py3.6.15-ocv4.8.0
    stdin_open: true
    tty: true
    network_mode: host
#    volumes:
#      - /tmp/argus_socket:/tmp/argus_socket
#      - /etc/enctune.conf:/etc/enctune.conf
#      - /etc/nv_tegra_release:/etc/nv_tegra_release
#      - /tmp/nv_jetson_model:/tmp/nv_jetson_model
#      - /home/jetson05/jetson-containers/data:/data
#      - /tmp/.X11-unix/:/tmp/.X11-unix
#      - /tmp/.docker.xauth:/tmp/.docker.xauth
#    devices:
#      - /dev/snd
#      - /dev/bus/usb
#      - /dev/video0
#    environment:
#      - DISPLAY=:0
#      - XAUTHORITY=/tmp/.docker.xauth
