version: "3"

# Example docker compose

services:

  app:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /tmp/:/tmp/  # Required for GUI
    environment:
      - DISPLAY=:0
